name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Create a Django project and configure settings
        run: |
          source .venv/bin/activate
          python -m django startproject mysite
          mv drf_redesign mysite/drf_redesign
          cd mysite
          echo "INSTALLED_APPS += ['drf_redesign', 'rest_framework']" >> mysite/settings.py

      - name: Run checks
        run: |
          source .venv/bin/activate
          cd mysite
          python manage.py check
