name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework drf-redesign
      - name: Create Django Project
        run: |
          python -m django startproject project
      - name: Add drf_redesign to INSTALLED_APPS
        run: |
          echo "INSTALLED_APPS += ['drf_redesign', 'rest_framework']" >> project/settings.py
      - name: Run Tests
        run: |
          cd project
          python manage.py test
